# A string used to distinguish different Supabase projects on the same host.
project_id = "base-app-template"

[api]
enabled = true
# Port to use for the API URL.
port = 54340
# Schemas to expose in your API.
schemas = ["public", "graphql_public"]
# Extra schemas to add to the search_path of every request.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returned by a query.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54341
# Port used by db diff command to initialize shadow db.
shadow_port = 54344
# The database major version to use.
major_version = 15

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54342
# External URL of the API server.
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54343
# Port for SMTP
smtp_port = 54345
# Port for POP3
pop3_port = 54346

[storage]
enabled = true
# Maximum file size allowed (50MB).
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website.
site_url = "http://localhost:3100"
# Allow/disallow new user signups via API.
enable_signup = true
# JWT expiry in seconds.
jwt_expiry = 3600

[auth.email]
# Allow/disallow new user signups via email.
enable_signup = true
# If enabled, double confirms email updates.
double_confirm_changes = true
# If enabled, requires email confirmation for new signups.
enable_confirmations = false

[auth.sms]
enable_signup = false

[auth.external.github]
enabled = false

[analytics]
enabled = true
port = 54347
backend = "postgres"